name: HouseDB tests
on: push
# includes code from https://github.com/francois2metz/pgtap-github-actions/blob/master/.github/workflows/pgtest.yml
# francois2metz

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:13
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install pg_prove
        run: sudo cpan TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash
      - name: Install postgres dev
        run: sudo apt-get install -y --no-install-recommends postgresql-server-dev-all
      - name: Checkout pgTAP
        uses: actions/checkout@v2
        with:
          repository: theory/pgtap
          path: pgtap
          ref: v1.1.0
      - name: install pgtap
        working-directory: pgtap
        run: make && psql --host postgres --username postgres --dbname postgres --file sql/pgtap.sql
        env:
          PGPASSWORD: postgres
      - name: Install database schema
        # Runs a script that creates a PostgreSQL client, populates
        # the client with data, and retrieves data
        run: PGPASSWORD=postgres psql -h postgres -U postgres -w -f install.sql
        # Environment variable used by the `client.js` script to create a new PostgreSQL client.
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432
      - name: Run tests
        run: pg_prove --host postgres -dbname postgres --suername postgres src/test/*_test.sql
        env:
          PGPASSWORD: postgres